/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AcademyRouteImport } from './routes/academy'
import { Route as AiGuideRouteImport } from './routes/ai-guide'
import { Route as BookRouteImport } from './routes/book'
import { Route as CitiesRouteImport } from './routes/cities'
import { Route as CoachesRouteImport } from './routes/coaches'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as EventsRouteImport } from './routes/events'
import { Route as GuidesRouteImport } from './routes/guides'
import { Route as LearningHubRouteImport } from './routes/learning-hub'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MembershipsRouteImport } from './routes/memberships'
import { Route as MobileAppRouteImport } from './routes/mobile-app'
import { Route as OpportunitiesRouteImport } from './routes/opportunities'
import { Route as PlayRouteImport } from './routes/play'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as SearchRouteImport } from './routes/search'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SportsRouteImport } from './routes/sports'
import { Route as StartFromZeroRouteImport } from './routes/start-from-zero'
import { Route as TalentScannerRouteImport } from './routes/talent-scanner'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ToolsRouteImport } from './routes/tools'
import { Route as TrainRouteImport } from './routes/train'
import { Route as TrialsRouteImport } from './routes/trials'
import { Route as VerifyRouteImport } from './routes/verify'
import { Route as BestToolsCategoryRouteImport } from './routes/best-tools.$category'
import { Route as CitySlugRouteImport } from './routes/city.$slug'
import { Route as GuideSlugRouteImport } from './routes/guide.$slug'
import { Route as SportInCitySlugRouteImport } from './routes/sport-in-city.$slug'
import { Route as SportSlugRouteImport } from './routes/sport.$slug'
import { Route as ToolsSlugRouteImport } from './routes/tools.$slug'
import { Route as TopGuidesCategoryRouteImport } from './routes/top-guides.$category'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademyRoute = AcademyRouteImport.update({
  id: '/academy',
  path: '/academy',
  getParentRoute: () => rootRouteImport,
} as any)
const AiGuideRoute = AiGuideRouteImport.update({
  id: '/ai-guide',
  path: '/ai-guide',
  getParentRoute: () => rootRouteImport,
} as any)
const BookRoute = BookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => rootRouteImport,
} as any)
const CitiesRoute = CitiesRouteImport.update({
  id: '/cities',
  path: '/cities',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachesRoute = CoachesRouteImport.update({
  id: '/coaches',
  path: '/coaches',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesRoute = GuidesRouteImport.update({
  id: '/guides',
  path: '/guides',
  getParentRoute: () => rootRouteImport,
} as any)
const LearningHubRoute = LearningHubRouteImport.update({
  id: '/learning-hub',
  path: '/learning-hub',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MembershipsRoute = MembershipsRouteImport.update({
  id: '/memberships',
  path: '/memberships',
  getParentRoute: () => rootRouteImport,
} as any)
const MobileAppRoute = MobileAppRouteImport.update({
  id: '/mobile-app',
  path: '/mobile-app',
  getParentRoute: () => rootRouteImport,
} as any)
const OpportunitiesRoute = OpportunitiesRouteImport.update({
  id: '/opportunities',
  path: '/opportunities',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayRoute = PlayRouteImport.update({
  id: '/play',
  path: '/play',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SportsRoute = SportsRouteImport.update({
  id: '/sports',
  path: '/sports',
  getParentRoute: () => rootRouteImport,
} as any)
const StartFromZeroRoute = StartFromZeroRouteImport.update({
  id: '/start-from-zero',
  path: '/start-from-zero',
  getParentRoute: () => rootRouteImport,
} as any)
const TalentScannerRoute = TalentScannerRouteImport.update({
  id: '/talent-scanner',
  path: '/talent-scanner',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsRoute = ToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainRoute = TrainRouteImport.update({
  id: '/train',
  path: '/train',
  getParentRoute: () => rootRouteImport,
} as any)
const TrialsRoute = TrialsRouteImport.update({
  id: '/trials',
  path: '/trials',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyRoute = VerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const BestToolsCategoryRoute = BestToolsCategoryRouteImport.update({
  id: '/best-tools/$category',
  path: '/best-tools/$category',
  getParentRoute: () => rootRouteImport,
} as any)
const CitySlugRoute = CitySlugRouteImport.update({
  id: '/city/$slug',
  path: '/city/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const GuideSlugRoute = GuideSlugRouteImport.update({
  id: '/guide/$slug',
  path: '/guide/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const SportInCitySlugRoute = SportInCitySlugRouteImport.update({
  id: '/sport-in-city/$slug',
  path: '/sport-in-city/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const SportSlugRoute = SportSlugRouteImport.update({
  id: '/sport/$slug',
  path: '/sport/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsSlugRoute = ToolsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ToolsRoute,
} as any)
const TopGuidesCategoryRoute = TopGuidesCategoryRouteImport.update({
  id: '/top-guides/$category',
  path: '/top-guides/$category',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/academy': typeof AcademyRoute
  '/ai-guide': typeof AiGuideRoute
  '/book': typeof BookRoute
  '/cities': typeof CitiesRoute
  '/coaches': typeof CoachesRoute
  '/community': typeof CommunityRoute
  '/dashboard': typeof DashboardRoute
  '/events': typeof EventsRoute
  '/guides': typeof GuidesRoute
  '/learning-hub': typeof LearningHubRoute
  '/login': typeof LoginRoute
  '/memberships': typeof MembershipsRoute
  '/mobile-app': typeof MobileAppRoute
  '/opportunities': typeof OpportunitiesRoute
  '/play': typeof PlayRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/resources': typeof ResourcesRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sports': typeof SportsRoute
  '/start-from-zero': typeof StartFromZeroRoute
  '/talent-scanner': typeof TalentScannerRoute
  '/terms': typeof TermsRoute
  '/tools': typeof ToolsRouteWithChildren
  '/train': typeof TrainRoute
  '/trials': typeof TrialsRoute
  '/verify': typeof VerifyRoute
  '/best-tools/$category': typeof BestToolsCategoryRoute
  '/city/$slug': typeof CitySlugRoute
  '/guide/$slug': typeof GuideSlugRoute
  '/sport-in-city/$slug': typeof SportInCitySlugRoute
  '/sport/$slug': typeof SportSlugRoute
  '/tools/$slug': typeof ToolsSlugRoute
  '/top-guides/$category': typeof TopGuidesCategoryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/academy': typeof AcademyRoute
  '/ai-guide': typeof AiGuideRoute
  '/book': typeof BookRoute
  '/cities': typeof CitiesRoute
  '/coaches': typeof CoachesRoute
  '/community': typeof CommunityRoute
  '/dashboard': typeof DashboardRoute
  '/events': typeof EventsRoute
  '/guides': typeof GuidesRoute
  '/learning-hub': typeof LearningHubRoute
  '/login': typeof LoginRoute
  '/memberships': typeof MembershipsRoute
  '/mobile-app': typeof MobileAppRoute
  '/opportunities': typeof OpportunitiesRoute
  '/play': typeof PlayRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/resources': typeof ResourcesRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sports': typeof SportsRoute
  '/start-from-zero': typeof StartFromZeroRoute
  '/talent-scanner': typeof TalentScannerRoute
  '/terms': typeof TermsRoute
  '/tools': typeof ToolsRouteWithChildren
  '/train': typeof TrainRoute
  '/trials': typeof TrialsRoute
  '/verify': typeof VerifyRoute
  '/best-tools/$category': typeof BestToolsCategoryRoute
  '/city/$slug': typeof CitySlugRoute
  '/guide/$slug': typeof GuideSlugRoute
  '/sport-in-city/$slug': typeof SportInCitySlugRoute
  '/sport/$slug': typeof SportSlugRoute
  '/tools/$slug': typeof ToolsSlugRoute
  '/top-guides/$category': typeof TopGuidesCategoryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/academy': typeof AcademyRoute
  '/ai-guide': typeof AiGuideRoute
  '/book': typeof BookRoute
  '/cities': typeof CitiesRoute
  '/coaches': typeof CoachesRoute
  '/community': typeof CommunityRoute
  '/dashboard': typeof DashboardRoute
  '/events': typeof EventsRoute
  '/guides': typeof GuidesRoute
  '/learning-hub': typeof LearningHubRoute
  '/login': typeof LoginRoute
  '/memberships': typeof MembershipsRoute
  '/mobile-app': typeof MobileAppRoute
  '/opportunities': typeof OpportunitiesRoute
  '/play': typeof PlayRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/resources': typeof ResourcesRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sports': typeof SportsRoute
  '/start-from-zero': typeof StartFromZeroRoute
  '/talent-scanner': typeof TalentScannerRoute
  '/terms': typeof TermsRoute
  '/tools': typeof ToolsRouteWithChildren
  '/train': typeof TrainRoute
  '/trials': typeof TrialsRoute
  '/verify': typeof VerifyRoute
  '/best-tools/$category': typeof BestToolsCategoryRoute
  '/city/$slug': typeof CitySlugRoute
  '/guide/$slug': typeof GuideSlugRoute
  '/sport-in-city/$slug': typeof SportInCitySlugRoute
  '/sport/$slug': typeof SportSlugRoute
  '/tools/$slug': typeof ToolsSlugRoute
  '/top-guides/$category': typeof TopGuidesCategoryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/academy'
    | '/ai-guide'
    | '/book'
    | '/cities'
    | '/coaches'
    | '/community'
    | '/dashboard'
    | '/events'
    | '/guides'
    | '/learning-hub'
    | '/login'
    | '/memberships'
    | '/mobile-app'
    | '/opportunities'
    | '/play'
    | '/pricing'
    | '/privacy'
    | '/resources'
    | '/search'
    | '/sitemap.xml'
    | '/sports'
    | '/start-from-zero'
    | '/talent-scanner'
    | '/terms'
    | '/tools'
    | '/train'
    | '/trials'
    | '/verify'
    | '/best-tools/$category'
    | '/city/$slug'
    | '/guide/$slug'
    | '/sport-in-city/$slug'
    | '/sport/$slug'
    | '/tools/$slug'
    | '/top-guides/$category'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/academy'
    | '/ai-guide'
    | '/book'
    | '/cities'
    | '/coaches'
    | '/community'
    | '/dashboard'
    | '/events'
    | '/guides'
    | '/learning-hub'
    | '/login'
    | '/memberships'
    | '/mobile-app'
    | '/opportunities'
    | '/play'
    | '/pricing'
    | '/privacy'
    | '/resources'
    | '/search'
    | '/sitemap.xml'
    | '/sports'
    | '/start-from-zero'
    | '/talent-scanner'
    | '/terms'
    | '/tools'
    | '/train'
    | '/trials'
    | '/verify'
    | '/best-tools/$category'
    | '/city/$slug'
    | '/guide/$slug'
    | '/sport-in-city/$slug'
    | '/sport/$slug'
    | '/tools/$slug'
    | '/top-guides/$category'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/academy'
    | '/ai-guide'
    | '/book'
    | '/cities'
    | '/coaches'
    | '/community'
    | '/dashboard'
    | '/events'
    | '/guides'
    | '/learning-hub'
    | '/login'
    | '/memberships'
    | '/mobile-app'
    | '/opportunities'
    | '/play'
    | '/pricing'
    | '/privacy'
    | '/resources'
    | '/search'
    | '/sitemap.xml'
    | '/sports'
    | '/start-from-zero'
    | '/talent-scanner'
    | '/terms'
    | '/tools'
    | '/train'
    | '/trials'
    | '/verify'
    | '/best-tools/$category'
    | '/city/$slug'
    | '/guide/$slug'
    | '/sport-in-city/$slug'
    | '/sport/$slug'
    | '/tools/$slug'
    | '/top-guides/$category'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AcademyRoute: typeof AcademyRoute
  AiGuideRoute: typeof AiGuideRoute
  BookRoute: typeof BookRoute
  CitiesRoute: typeof CitiesRoute
  CoachesRoute: typeof CoachesRoute
  CommunityRoute: typeof CommunityRoute
  DashboardRoute: typeof DashboardRoute
  EventsRoute: typeof EventsRoute
  GuidesRoute: typeof GuidesRoute
  LearningHubRoute: typeof LearningHubRoute
  LoginRoute: typeof LoginRoute
  MembershipsRoute: typeof MembershipsRoute
  MobileAppRoute: typeof MobileAppRoute
  OpportunitiesRoute: typeof OpportunitiesRoute
  PlayRoute: typeof PlayRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  ResourcesRoute: typeof ResourcesRoute
  SearchRoute: typeof SearchRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SportsRoute: typeof SportsRoute
  StartFromZeroRoute: typeof StartFromZeroRoute
  TalentScannerRoute: typeof TalentScannerRoute
  TermsRoute: typeof TermsRoute
  ToolsRoute: typeof ToolsRouteWithChildren
  TrainRoute: typeof TrainRoute
  TrialsRoute: typeof TrialsRoute
  VerifyRoute: typeof VerifyRoute
  BestToolsCategoryRoute: typeof BestToolsCategoryRoute
  CitySlugRoute: typeof CitySlugRoute
  GuideSlugRoute: typeof GuideSlugRoute
  SportInCitySlugRoute: typeof SportInCitySlugRoute
  SportSlugRoute: typeof SportSlugRoute
  TopGuidesCategoryRoute: typeof TopGuidesCategoryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academy': {
      id: '/academy'
      path: '/academy'
      fullPath: '/academy'
      preLoaderRoute: typeof AcademyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-guide': {
      id: '/ai-guide'
      path: '/ai-guide'
      fullPath: '/ai-guide'
      preLoaderRoute: typeof AiGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book': {
      id: '/book'
      path: '/book'
      fullPath: '/book'
      preLoaderRoute: typeof BookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cities': {
      id: '/cities'
      path: '/cities'
      fullPath: '/cities'
      preLoaderRoute: typeof CitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coaches': {
      id: '/coaches'
      path: '/coaches'
      fullPath: '/coaches'
      preLoaderRoute: typeof CoachesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides': {
      id: '/guides'
      path: '/guides'
      fullPath: '/guides'
      preLoaderRoute: typeof GuidesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learning-hub': {
      id: '/learning-hub'
      path: '/learning-hub'
      fullPath: '/learning-hub'
      preLoaderRoute: typeof LearningHubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memberships': {
      id: '/memberships'
      path: '/memberships'
      fullPath: '/memberships'
      preLoaderRoute: typeof MembershipsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mobile-app': {
      id: '/mobile-app'
      path: '/mobile-app'
      fullPath: '/mobile-app'
      preLoaderRoute: typeof MobileAppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/opportunities': {
      id: '/opportunities'
      path: '/opportunities'
      fullPath: '/opportunities'
      preLoaderRoute: typeof OpportunitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play': {
      id: '/play'
      path: '/play'
      fullPath: '/play'
      preLoaderRoute: typeof PlayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sports': {
      id: '/sports'
      path: '/sports'
      fullPath: '/sports'
      preLoaderRoute: typeof SportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/start-from-zero': {
      id: '/start-from-zero'
      path: '/start-from-zero'
      fullPath: '/start-from-zero'
      preLoaderRoute: typeof StartFromZeroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/talent-scanner': {
      id: '/talent-scanner'
      path: '/talent-scanner'
      fullPath: '/talent-scanner'
      preLoaderRoute: typeof TalentScannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools': {
      id: '/tools'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof ToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/train': {
      id: '/train'
      path: '/train'
      fullPath: '/train'
      preLoaderRoute: typeof TrainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trials': {
      id: '/trials'
      path: '/trials'
      fullPath: '/trials'
      preLoaderRoute: typeof TrialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify': {
      id: '/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof VerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/best-tools/$category': {
      id: '/best-tools/$category'
      path: '/best-tools/$category'
      fullPath: '/best-tools/$category'
      preLoaderRoute: typeof BestToolsCategoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/city/$slug': {
      id: '/city/$slug'
      path: '/city/$slug'
      fullPath: '/city/$slug'
      preLoaderRoute: typeof CitySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guide/$slug': {
      id: '/guide/$slug'
      path: '/guide/$slug'
      fullPath: '/guide/$slug'
      preLoaderRoute: typeof GuideSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sport-in-city/$slug': {
      id: '/sport-in-city/$slug'
      path: '/sport-in-city/$slug'
      fullPath: '/sport-in-city/$slug'
      preLoaderRoute: typeof SportInCitySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sport/$slug': {
      id: '/sport/$slug'
      path: '/sport/$slug'
      fullPath: '/sport/$slug'
      preLoaderRoute: typeof SportSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/$slug': {
      id: '/tools/$slug'
      path: '/$slug'
      fullPath: '/tools/$slug'
      preLoaderRoute: typeof ToolsSlugRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/top-guides/$category': {
      id: '/top-guides/$category'
      path: '/top-guides/$category'
      fullPath: '/top-guides/$category'
      preLoaderRoute: typeof TopGuidesCategoryRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ToolsRouteChildren {
  ToolsSlugRoute: typeof ToolsSlugRoute
}

const ToolsRouteChildren: ToolsRouteChildren = {
  ToolsSlugRoute: ToolsSlugRoute,
}

const ToolsRouteWithChildren = ToolsRoute._addFileChildren(ToolsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AcademyRoute: AcademyRoute,
  AiGuideRoute: AiGuideRoute,
  BookRoute: BookRoute,
  CitiesRoute: CitiesRoute,
  CoachesRoute: CoachesRoute,
  CommunityRoute: CommunityRoute,
  DashboardRoute: DashboardRoute,
  EventsRoute: EventsRoute,
  GuidesRoute: GuidesRoute,
  LearningHubRoute: LearningHubRoute,
  LoginRoute: LoginRoute,
  MembershipsRoute: MembershipsRoute,
  MobileAppRoute: MobileAppRoute,
  OpportunitiesRoute: OpportunitiesRoute,
  PlayRoute: PlayRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  ResourcesRoute: ResourcesRoute,
  SearchRoute: SearchRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SportsRoute: SportsRoute,
  StartFromZeroRoute: StartFromZeroRoute,
  TalentScannerRoute: TalentScannerRoute,
  TermsRoute: TermsRoute,
  ToolsRoute: ToolsRouteWithChildren,
  TrainRoute: TrainRoute,
  TrialsRoute: TrialsRoute,
  VerifyRoute: VerifyRoute,
  BestToolsCategoryRoute: BestToolsCategoryRoute,
  CitySlugRoute: CitySlugRoute,
  GuideSlugRoute: GuideSlugRoute,
  SportInCitySlugRoute: SportInCitySlugRoute,
  SportSlugRoute: SportSlugRoute,
  TopGuidesCategoryRoute: TopGuidesCategoryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
